### PR TITLE
Remove version from pubspec

### PR DESCRIPTION
**Pull request by kevmoo**
Not meant to be published

### CODE REVIEW

**Comment by kevmoo** [comment]
@aam – cool?

**Comment by aam** [comment]
> @aam – cool?

Sorry missed this @kevmoo .
What is the meaning of version removal, why would you want to do that? Immediate thoughts are the version number is useful thing for the package.

**Comment by kevmoo** [comment]
Only useful for publishing the package. Not having the version makes it clear that this is not something that's published.

**Comment by aam** [comment]
Cool, makes sense.

**Review by aam — APPROVED** [review]

**Pull request merged**
